GET http://localhost:8080/places

###

GET http://localhost:8080/places/60958d6383943512bcab5343

###

POST http://localhost:8080/places
Content-Type: application/json

{
    "name": "Sea",
    "location": "Israel",
    "description": "yes yes"
}

###

DELETE http://localhost:8080/places/60958d6383943512bcab5343

###

PATCH http://localhost:8080/places/60958d6383943512bcab5343
Content-Type: application/json

{
    "name": "new place"
}